inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 160

Style/AsciiComments:
  Enabled: false

